version: '3.8'

services:
  temp-mail-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./email:/app/email
      - ./main.log:/app/main.log
    restart: always